FROM alpine:3.4

MAINTAINER Daniel Hiltgen <daniel.hiltgen@docker.com>

ARG MACHINE_VERSION
# Uncomment the following line to build with docker engine < 1.13
# ARG GO_VERSION
ENV GOPATH /go

RUN apk -v add --update libvirt-dev curl go git musl-dev gcc
RUN git clone --branch ${MACHINE_VERSION} https://github.com/docker/machine.git /go/src/github.com/docker/machine
